import Row from "react-bootstrap/Row";
import React from "react";
import { useSelector, useDispatch } from "react-redux";
import { useEffect, useState } from "react";
import styles from "@/styles/Home.module.css";
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
  useDisclosure,
  Input,
  Button,
  Link,
  Container,
  Flex,
  Spacer,
} from "@chakra-ui/react";
import { Col } from "react-bootstrap";
import {
  Slider,
  SliderTrack,
  SliderFilledTrack,
  SliderThumb,
  SliderMark,
} from "@chakra-ui/react";
import { Stack, HStack, VStack } from "@chakra-ui/react";

import Head from "next/head";
import SidebarWithHeader from "@/components/SidebarWithHeader";
import AddProduct from "@/components/AddProduct";

function admindesboard() {
  const { isLoggedIn, user } = useSelector((state) => state.auth);
  const { isOpen, onOpen, onClose } = useDisclosure();
  const btnRef = React.useRef();
  const [selectedImage, setSelectedImage] = useState(null);
  const [url, setUrl] = useState("");

  async function uploadFile() {
    const data = new FormData();
    data.append("image", selectedImage);
    const url = `https://api.imgbb.com/1/upload?key=`;
    const upload = await fetch(url, {
      method: "POST",
      body: data,
    })
      .then((r) => r.json())
      .then((r) => setUrl(r.data.url));

    return upload?.data?.url;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoggedIn && (
        <SidebarWithHeader>
          <VStack>
            <h2>admindesboard: hola admin</h2>

            <input
              type="file"
              name="myImage"
              onChange={(event) => {
                console.log(event.target.files[0]);
                setSelectedImage(event.target.files[0]);
              }}
            />
            <input type="submit" value="enviar" onClick={uploadFile} />

            {url && (
              <div>
                <img alt="not found" width={"250px"} src={url} />
                <br />
                <button onClick={() => setUrl(null)}>Remove</button>
              </div>
            )}
            <AddProduct/>
          </VStack>
        </SidebarWithHeader>
      )}
    </>
  );
}

export default admindesboard;
