import Row from "react-bootstrap/Row";
import React from "react";
import { useSelector, useDispatch } from "react-redux";
import { useEffect, useState } from "react";
import styles from "@/styles/Home.module.css";
import {
  Drawer,
  DrawerBody,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerContent,
  DrawerCloseButton,
  useDisclosure,
  Input,
  Button,
  Link,
  Container,
  Flex,
  Spacer,
} from "@chakra-ui/react";
import { Col } from "react-bootstrap";
import {
  Slider,
  SliderTrack,
  SliderFilledTrack,
  SliderThumb,
  SliderMark,
} from "@chakra-ui/react";
import { Stack, HStack, VStack } from "@chakra-ui/react";

import Head from "next/head";
import SidebarWithHeader from "@/components/SidebarWithHeader";
import AddProduct from "@/components/AddProduct";

function admindesboard() {
  const { isLoggedIn, user } = useSelector((state) => state.auth);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoggedIn && (
        <SidebarWithHeader>
          <VStack>
            <h2>admindesboard: hola admin</h2>
            <AddProduct />
          </VStack>
        </SidebarWithHeader>
      )}
    </>
  );
}

export default admindesboard;
