import React from "react";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import SidebarWithHeader from "@/components/SidebarWithHeader";
import GetAllProducts from "@/components/GetAllProducts";

function products() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SidebarWithHeader>
        <h1>All products</h1>
        <GetAllProducts />
      </SidebarWithHeader>
    </div>
  );
}

export default products;
