import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Col, Navbar, Row } from "react-bootstrap";
const inter = Inter({ subsets: ["latin"] });
import { useSelector, useDispatch } from "react-redux";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Navbr from "@/components/Navbr";
import Hero from "@/components/Hero";
import AddProduct from "@/components/AddProduct";
import GetAllProducts from "@/components/GetAllProducts";
import { Center, Container } from "@chakra-ui/react";

export default function Home() {
  const { push } = useRouter();
  const { isLoggedIn, user } = useSelector((state) => state.auth);

  return (
    <>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbr />
        <main className={styles.main}>
          <Container maxW={"8xl"}>
            <Hero isLoggedIn={isLoggedIn} />
            <Center>
              <GetAllProducts />
            </Center>
          </Container>
        </main>
      </>
    </>
  );
}
