import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Col, Container, Row } from "react-bootstrap";
const inter = Inter({ subsets: ["latin"] });
import { useSelector, useDispatch } from "react-redux";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const { push } = useRouter();
  const { isLoggedIn, user } = useSelector((state) => state.auth);

  return (
    <>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Container>
            <h1>hello index. home page</h1>
            {!isLoggedIn ? (
              <Row>
                <Col>
                  <Link href="/register">registrarme</Link>
                </Col>
                <Col>
                  <Link href="/login">Ya tengo una cuenta</Link>
                </Col>
              </Row>
            ) : (
              <Row>
                <h2>usted ya se encuentra logeado</h2>
              </Row>
            )}
          </Container>
        </main>
      </>
    </>
  );
}
