import Login from "@/components/Login";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbr from "@/components/Navbr";
import { useDisclosure } from "@chakra-ui/react";

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbr onOpen={onOpen} />
      <main className={styles.main}>
        <Login />
      </main>
    </>
  );
}
