import Navbr from "@/components/Navbr";
import { useDisclosure } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import { Container, Row } from "react-bootstrap";
import { useSelector } from "react-redux";
import styles from "@/styles/Home.module.css";

function userdesboard() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const { isLoggedIn, user } = useSelector((state) => state.auth);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbr onOpen={onOpen} />
      <main className={styles.main}>
        <h2>esa user</h2>
      </main>
    </>
  );
}

export default userdesboard;
